---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint .
platforms:
  - name: deploy-da-bomb
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys:/sys:ro
      - /var/lib/containerd
    privileged: true
    cgroupns_mode: host
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
