---
- name: Build the application locally
  delegate_to: localhost
  community.docker.docker_image:
    name: "{{ docker_image_name }}"
    tag: "{{ docker_image_tag }}"
    build:
      path: "{{ app_dir }}"
  register: build_result
